### ISSUE TITLE
Docker + osx not working

### ISSUE THREAD

**Issue by AdriVanHoudt** [Imgur/incus#56]
We are looking into using incus, it looks really nice, but I couldn't get it to work with Docker. I am not experienced with it but the incus image could not connect to the redis image. I followed all the commands in the readme and both downloaded and 'work' apart from the connecting part.
See https://gist.github.com/AdriVanHoudt/b71c181a00289fbd9fbf

**Comment by jacob-pascual** [comment]
Can you paste the output of this shell command?

`$ docker run --link incusredis:redis jwgur/incus env`

**Comment by AdriVanHoudt** [comment]
``` bash
$ docker run --link incusredis:redis jwgur/incus env
PATH=/go/bin:/usr/src/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=eb381f10fb02
REDIS_PORT=tcp://172.17.0.9:6379
REDIS_PORT_6379_TCP=tcp://172.17.0.9:6379
REDIS_PORT_6379_TCP_ADDR=172.17.0.9
REDIS_PORT_6379_TCP_PORT=6379
REDIS_PORT_6379_TCP_PROTO=tcp
REDIS_NAME=/clever_jones/redis
REDIS_ENV_REDIS_VERSION=3.0.3
REDIS_ENV_REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-3.0.3.tar.gz
REDIS_ENV_REDIS_DOWNLOAD_SHA1=0e2d7707327986ae652df717059354b358b83358
GOLANG_VERSION=1.4.2
GOPATH=/go
HOME=/root
```

**Comment by jacob-pascual** [comment]
It's hard to tell what commands you ran in the gist you sent me. The command to start Incus (under Docker) should be:

`$ docker run --env-file=incus.conf -e REDIS_ENABLED=true --link incusredis:redis -p 4000:4000 jwgur/incus`

The message you saw (`2015/08/25 16:23:51 Redis connect failed: dial tcp 127.0.0.1:6379: connection refused`) can only occur when the environment variable `REDIS_PORT_6379_TCP_ADDR` is not set, as `127.0.0.1` is [its default value](https://github.com/Imgur/incus/blob/master/config.go#L31). `--link` tells docker to set that environment variable, so try running that exact command as pasted above?

**Comment by AdriVanHoudt** [comment]
I ran the exact commands that are in the readme https://github.com/Imgur/incus#method-1-docker
and hmm some stuff got cut off it seems
Let me do it again from scratch and produce a new gist

hmm but according to the last paste the redis should be @ tcp://172.17.0.9:6379 and not 127.0.01:6379?

**Comment by AdriVanHoudt** [comment]
ok updated the gist https://gist.github.com/AdriVanHoudt/b71c181a00289fbd9fbf

**Comment by jacob-pascual** [comment]
@AdriVanHoudt Perhaps `--env-file` is overwriting the link environment variables. Try removing [these](https://github.com/Imgur/incus/blob/master/incus.conf#L21-L23) lines from your incus.conf?

**Comment by AdriVanHoudt** [comment]
that seems to work thanks! any tips on how to start using it? the incusjs module does not work for node

**Comment by jacob-pascual** [comment]
What's wrong with the incusjs module on node?

**Comment by AdriVanHoudt** [comment]
just doing 

``` js
var IncusClient = require('incusjs');

var incus = new IncusClient('http://localhost:4000', 'UID', '/page/path');
```

results in 

``` js
/Users/adri/Projects/.../incus/node_modules/incusjs/src/incus.js:29
    this.poll = new XMLHttpRequest();
                    ^
ReferenceError: XMLHttpRequest is not defined
    at Incus.longpoll (/Users/adri/Projects/.../incus/node_modules/incusjs/src/incus.js:29:21)
    at Incus.connect (/Users/adri/Projects/.../incus/node_modules/incusjs/src/incus.js:78:10)
    at new Incus (/Users/adri/Projects/.../incus/node_modules/incusjs/src/incus.js:19:10)
    at Object.<anonymous> (/Users/adri/Projects/.../incus/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by jacob-pascual** [comment]
Oh, right. We are gonna be transitioning to use `request` or something, but for now `incusjs` is just for the browser.

**Comment by AdriVanHoudt** [comment]
I can probably shim it with https://www.npmjs.com/package/xmlhttprequest
Can I recommend https://www.npmjs.com/package/wreck ? ;)

**Comment by AdriVanHoudt** [comment]
`window is not defined`...

Can you give a quick guide/tips on how to communicate with the docker/incus? Then I can make it myself for node (will oss it ofc)

Also I will close the issue now since the original question was answered

**Comment by jacob-pascual** [comment]
@AdriVanHoudt Incus listens on port 4000. You can, for example, curl `/lp` to long-poll over HTTP:

```
$ curl -i http://rt.imgur.com/lp?page=/gallery/ADxBC1S\&user=foo
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Type: application/json
Date: Thu, 27 Aug 2015 09:40:18 GMT
Content-Length: 89

{"event":"imagePoints","data":{"downs":32,"hash":"ADxBC1S","ups":1215},"time":1440668418}
```

Or you can use the `incusjs` library in the browser to use websockets.

**Comment by AdriVanHoudt** [comment]
ok cool, looking at the incusjs to see how to talk to injus rest wise
seems a bit weird to do GET that results in sending out a notification but ok ^^
Once I am done I might do a pr with some docs or just make a node module with all the info

**Comment by AdriVanHoudt** [comment]
ok having some troubles setting it up further. I need to publish to the redis, which does not have an open port? So I tried a local redis but Incus won't connect to it
Also tried `docker run --env-file incus.conf -d -e REDIS_PORT_6379_TCP_ADDR=dockerhost -e REDIS_PORT_6379_TCP_PORT=6379 --add-host=dockerhost:127.0.0.1  --name incus -e REDIS_ENABLED=true -p 4000:4000 jwgur/incus` with no result

**Comment by AdriVanHoudt** [comment]
ok so I exposed the redis port like the Incus port and I have found out how docker on mac works and that it needs special care with ip addresses (since docker is ran inside a virtual box), all good now
