### ISSUE TITLE
Websockets not working

### ISSUE THREAD

**Issue by AdriVanHoudt** [Imgur/incus#59]
I am using incusjs to connect to incus on the client side (where you should really do either poll or websocket and not abort the poll when websocket comes through, this leaves Incus thinking there are 2 connections while this is not true if you are open I will do a PR for this)

I am using this command

``` json5
{
    "command": {
        "command": "pushormessage",
        "user": "user1"
    },
    "message": {
        "time": 0,
        "websocket": {
            "event": "test",
            "data": {...},
            "time": 0
        }
    }
}
```

And I am doing both (normally only lpush needed right?)

``` js
redis.publish('Incus', JSON.stringify(command));
redis.lpush('Incus_Queue', JSON.stringify(command));
```

but none seem to trigger Incus to use the websocket

**Comment by AdriVanHoudt** [comment]
It appears the redis polling is not working to well.
I have debug on and I never see this getting printed https://github.com/Imgur/incus/blob/8d1d7d3b700a4bc238c3c78578ca11233699b7c2/server.go#L245 and no error appears
I just see 

``` bash
2015/08/31 11:07:04 Incus built on .20150821.004222-58efc50c132951e478f9ac8b9c493264e409eea0*
2015/08/31 11:07:04 There are 0 connected clients
2015/08/31 11:07:22 Long poll connected via 
2015/08/31 11:07:22 saving UID as user1
2015/08/31 11:07:24 There are 1 connected clients
2015/08/31 11:07:44 There are 1 connected clients
2015/08/31 11:08:04 There are 1 connected clients
2015/08/31 11:08:24 There are 1 connected clients
2015/08/31 11:08:37 Socket connected via 192.168.99.1:51207
2015/08/31 11:08:37 map[user:user1 command:authenticate]
2015/08/31 11:08:37 saving UID as user1
2015/08/31 11:08:44 There are 2 connected clients
2015/08/31 11:09:04 There are 2 connected clients
```

And the list stays full so nothing is getting handled.

**Comment by briankassouf** [comment]
@AdriVanHoudt The long poll abort is intentional (fallback-based connections vs upgrade-based connections) 

However it does appear Incus is not listening on redis. Did you correctly set all the redis environment variables? https://github.com/Imgur/incus/blob/master/config.go#L27

**Comment by AdriVanHoudt** [comment]
Derp seems like somehow I forgot to copy over the `enable redis` var
Did you read my comment between the () though?
Let me verify my monday fail

**Comment by AdriVanHoudt** [comment]
ok so my `REDIS_ENABLED` was set to false :sweat_smile: 
now I have the whole thing running but still websockets not working

incus log:

``` bash
2015/09/01 08:31:03 Incus built on .20150821.004222-58efc50c132951e478f9ac8b9c493264e409eea0*
2015/09/01 08:31:03 There are 0 pending commands
2015/09/01 08:31:03 There are 0 connected clients
2015/09/01 08:31:04 LISENING FOR REDIS MESSAGE
2015/09/01 08:31:04 Handling redis message of type pushormessage
2015/09/01 08:31:21 Socket connected via 192.168.99.1:55785
2015/09/01 08:31:21 map[user:user1 command:authenticate]
2015/09/01 08:31:21 saving UID as user1
2015/09/01 08:31:23 There are 1 connected clients
2015/09/01 08:31:27 Handling redis message of type pushormessage
2015/09/01 08:31:43 There are 1 connected clients
2015/09/01 08:32:01 Handling redis message of type pushormessage
2015/09/01 08:32:03 There are 1 connected clients
2015/09/01 08:32:23 There are 1 connected clients
2015/09/01 08:32:43 There are 1 connected clients
2015/09/01 08:33:01 Handling redis message of type pushormessage
2015/09/01 08:33:03 There are 1 connected clients
2015/09/01 08:33:23 There are 1 connected clients
2015/09/01 08:33:43 There are 1 connected clients
2015/09/01 08:34:03 There are 1 connected clients
2015/09/01 08:34:23 There are 1 connected clients
2015/09/01 08:34:43 There are 1 connected clients
```

message set was 
`{"command":{"command":"pushormessage"},"message":{"time":0,"websocket":{"event":"test","data":{"id":1},"time":0}}}`

message never got on the client
client was authenticated 
![](http://puu.sh/jW2dd/031dcc8fdb.png)

**Comment by briankassouf** [comment]
@AdriVanHoudt could you try replacing `pushormessage` with just `message` like so:
`{"command":{"command":"message"},"message":{"time":0,"websocket":{"event":"test","data":{"id":1},"time":0}}}`

**Comment by AdriVanHoudt** [comment]
doesn't work, also I want to enable gcm and ans in the future

**Comment by briankassouf** [comment]
Sorry meant like: `{"command":{"command":"message"},"message":{"event":"test","data":{"id":1},"time":0}}`

**Comment by AdriVanHoudt** [comment]
If I specify a use it prints `2015/09/01 09:12:47 Handling redis message of type message
2015/09/01 09:12:47 Error formatting message: Could not format message` if no user it doesn't
I assume because https://github.com/Imgur/incus/blob/master/message.go#L282 is not done in `messageAll` also with that I need to publish it instad of lpush right?

**Comment by AdriVanHoudt** [comment]
Sending just the message works :raised_hands: now to get it working with the `pushormessage` :P

**Comment by briankassouf** [comment]
:+1: try using this json:

`{"command":{"command":"pushormessage", "user": "user1"}, "message":{"websocket":{"event":"test","data":{"id":1},"time":0}, "time": 0}}`

**Comment by AdriVanHoudt** [comment]
just did, nothing happens, only thing I can see is https://github.com/Imgur/incus/blob/master/message.go#L126 returning `active=false`

**Comment by briankassouf** [comment]
Ah okay, are you using the incusjs code for connecting the websockets?

**Comment by briankassouf** [comment]
On the client side your websocket needs to send up its active status. This can be done using our incusjs presence class:
https://github.com/Imgur/incusjs/blob/master/src/lib/presence.js

Or by sending up a command that meets this requirement: 
https://github.com/Imgur/incus/blob/master/message.go#L63

**Comment by AdriVanHoudt** [comment]
yes using incusjs and oh that is not documented anywhere :O

**Comment by briankassouf** [comment]
@AdriVanHoudt Yeah, sorry about that. This feature is really, really new. We will do a better job of documenting new features in the future!

**Comment by AdriVanHoudt** [comment]
it is a pretty cool one though, will try right now.

**Comment by AdriVanHoudt** [comment]
ok I setted the presence ![](http://puu.sh/jW5oe/9d17da821c.png)
still does not do anything :sob: 
also I think https://github.com/Imgur/incusjs/blob/master/src/lib/presence.js#L54 needs to be `presence` not `present` see https://github.com/Imgur/incus/blob/master/message.go#L64

**Comment by AdriVanHoudt** [comment]
but I am setting it manually so no problem with that atm

**Comment by AdriVanHoudt** [comment]
Ok so we decided that we always want to send to browser AND phones (at least for now) so I just push 3 commands (ios, android, browser) and that works.
- the previous stuff is still an issue
- the fact that incusjs does polling first and then aborts is fine although Incus thinks there are 2 clients connected when that happens, it even seems the count never goes down? https://github.com/Imgur/incus/search?utf8=%E2%9C%93&q=clientCount

**Comment by briankassouf** [comment]
Closing in favor of issues in the incusjs repo
