### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by AdriVanHoudt** [Imgur/incus#64]
Is there a recommended way of updating the docker image (on my end) I have not used it very much so no idea how I can follow the latest release from Incus

**Comment by AdriVanHoudt** [comment]
Any help on this? I would really like to keep my version of incus up to date

**Comment by jacob-pascual** [comment]
https://hub.docker.com/r/imgur/incus/ is automatically updated (automatic build). I will update the documentation to reflect that.

**Comment by AdriVanHoudt** [comment]
cool, thanks!
Is https://github.com/Imgur/incus/commit/893e2d4de3d5dadd811cb35ca6c39c32e304ad87 included in the new one? I seem to disconnect sockets after 60 seconds. Tested and it follows https://github.com/Imgur/incus/blob/master/config.yml#L8 which should not happen (and it is a short default anyway)

**Comment by jacob-pascual** [comment]
Incus prints what version (git SHA-1 hash) it was built as on startup.

**Comment by AdriVanHoudt** [comment]
Not sure how to calculate that (commit sha?)
Also https://hub.docker.com/r/imgur/incus/ does not even have the latests readme updates( this commit is not in it https://github.com/Imgur/incus/commit/be94ad9d52a6516cc0773bc8d08233987f3726c2), so this means it is outdated? 
`docker pull imgur/incus` tells me I have the latest which I doubt since there was an update today

**Comment by AdriVanHoudt** [comment]
The Docker image still does not seem update, is this possible?
